# Generated by Django 5.0.14 on 2026-07-15 13:46

import core.models
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="Job title / Degree / Skill category name",
                        max_length=200,
                    ),
                ),
                (
                    "subheading",
                    models.CharField(
                        blank=True, help_text="Company / Institution", max_length=200
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="One-line summary shown even when the card is collapsed.",
                        max_length=300,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Entries",
                "ordering": ["order", "-start_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                (
                    "headline",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Senior Backend Engineer",
                        max_length=200,
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                (
                    "summary",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, help_text="Optional short intro paragraph."
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile",
                "verbose_name_plural": "Profile",
            },
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "layout",
                    models.CharField(
                        choices=[
                            (
                                "timeline",
                                "Timeline — dated entries with expandable bullets (e.g. Employment, Education)",
                            ),
                            (
                                "skills",
                                "Skills — categories of tags, expandable per category",
                            ),
                            (
                                "text",
                                "Text block — a simple rich-text blob, no entries",
                            ),
                        ],
                        default="timeline",
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive sections are hidden everywhere, including the portal builder.",
                    ),
                ),
                (
                    "intro_text",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="Optional text shown under the section title (used by 'Text block' layout).",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="DetailItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(
                        help_text="For Skills entries, just the skill name; formatting is ignored there."
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="core.entry",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProfileLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50)),
                ("url", models.URLField()),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="core.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="PublicPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        default=core.models.generate_slug,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("employer_name", models.CharField(max_length=200)),
                ("position_title", models.CharField(blank=True, max_length=200)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Private notes about this application. Never shown publicly.",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="If off, the link 404s for the public but still works for you when logged in.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "details",
                    models.ManyToManyField(
                        blank=True, related_name="public_pages", to="core.detailitem"
                    ),
                ),
                (
                    "entries",
                    models.ManyToManyField(
                        blank=True, related_name="public_pages", to="core.entry"
                    ),
                ),
                (
                    "sections",
                    models.ManyToManyField(
                        blank=True, related_name="public_pages", to="core.section"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=300)),
                ("referrer", models.CharField(blank=True, max_length=300)),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_views",
                        to="core.publicpage",
                    ),
                ),
            ],
            options={
                "ordering": ["-viewed_at"],
            },
        ),
        migrations.AddField(
            model_name="entry",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="entries",
                to="core.section",
            ),
        ),
    ]
